/* © 2026 FlowCognition by suvilab.com — Tüm hakları saklıdır. */
"use strict";
const sec = ad => document.getElementById(ad);
const adlar = {md_mm:"Mesial (+) / distal (−) · mm",bl_mm:"Bukkal (+) / lingual (−) · mm",ie_mm:"İntrüzyon (+) / ekstrüzyon (−) · mm",rotasyon_derece:"Rotasyon · derece",tip_derece:"Tip · derece",tork_derece:"Tork · derece"};
const durumlar = {geometri_bekleniyor:"Taslak · CAD geometri denetimi bekleniyor",geometri_denetimli_taslak:"Geometri denetimli taslak · klinik onay değil",veri_yetersiz:"Eksik veri nedeniyle durduruldu",engellendi:"Bildirilen risk nedeniyle engellendi",cozum_bulunamadi:"Kısıtlar altında çözüm bulunamadı",asama_siniri:"Aşama sınırına ulaşıldı",denetci_hatasi:"Geometri denetçisi hatası",hareket_yok:"Hareket yok"};
let veri, sonuc;
function oge(tur,metin,sinif){const e=document.createElement(tur);if(metin!==undefined)e.textContent=metin;if(sinif)e.className=sinif;return e;}
function temizle(){sonuc=undefined;sec("indir").disabled=true;sec("asama").disabled=true;sec("asamaNo").textContent="—";for(const ad of ["butceler","asamaSatirlari","zaman"])sec(ad).replaceChildren();sec("butceAciklama").textContent="Güncel bütçe için yeniden hesaplayın.";sec("ozet").replaceChildren(oge("p","Girdi değişti. Güncel sonuç için yeniden hesaplayın."));}
function yaz(){sec("girdi").value=JSON.stringify(veri,null,2);temizle();}
function seciliDis(){return veri.disler.find(d=>d.fdi===Number(sec("dis").value));}
function disGoster(){const d=seciliDis();sec("hareketler").replaceChildren();if(!d)return;for(const [ad,baslik] of Object.entries(adlar)){const kutu=oge("div"),etiket=oge("label",baslik),girdi=oge("input");girdi.id=ad;etiket.htmlFor=ad;girdi.type="number";girdi.step=ad.endsWith("mm")?"0.01":"0.1";girdi.value=d.hareket[ad];girdi.addEventListener("input",()=>{d.hareket[ad]=girdi.value===""?null:Number(girdi.value);yaz();});kutu.append(etiket,girdi);sec("hareketler").append(kutu);}sec("atasman").value=d.atasman;butceGoster();}
function formKur(){if(!veri||!Array.isArray(veri.disler)||!veri.disler.length||veri.disler.some(d=>!d||!d.hareket))throw new Error("Diş listesi ve hareket alanları gerekli.");sec("dis").replaceChildren(...veri.disler.map(d=>{const e=oge("option",`Diş ${d.fdi}`);e.value=d.fdi;return e;}));sec("dis").value=veri.disler.some(d=>d.fdi===13)?13:veri.disler[0].fdi;for(const ad of ["dis","atasman","strateji"])sec(ad).disabled=false;sec("strateji").value=veri.strateji;disGoster();}
async function ornek(){try{veri=await(await fetch("/api/v1/ornek")).json();temizle();formKur();yaz();sec("hata").textContent="";}catch(h){sec("hata").textContent=h.message;}}
sec("ornek").addEventListener("click",ornek);sec("dis").addEventListener("change",disGoster);
sec("atasman").addEventListener("change",()=>{seciliDis().atasman=sec("atasman").value;yaz();});sec("strateji").addEventListener("change",()=>{veri.strateji=sec("strateji").value;yaz();});
sec("girdi").addEventListener("input",()=>{temizle();sec("hareketler").replaceChildren(oge("p","Hızlı alanları güncellemek için JSON’u forma aktarın."));for(const ad of ["dis","atasman","strateji"])sec(ad).disabled=true;});
sec("aktar").addEventListener("click",()=>{try{veri=JSON.parse(sec("girdi").value);temizle();formKur();sec("hata").textContent="";}catch(h){sec("hata").textContent=h.message;}});
function butceGoster(){if(!sonuc)return;const d=sonuc.disler.find(d=>d.fdi===Number(sec("dis").value));if(!d)return;sec("butceler").replaceChildren();sec("butceAciklama").textContent=`Diş ${d.fdi} · Katsayılar klinik olarak kalibre edilmemiştir. Yön bilgisi bütçe seçiminde korunur.`;for(const [ad,b] of Object.entries(d.butceler)){const satir=oge("tr");for(const metin of [adlar[ad],b.temel.tercih.toFixed(3),b.tercih.toFixed(3),b.uyari.toFixed(3),b.azami.toFixed(3),b.katsayi.toFixed(3),b.iz.map(i=>`${i.neden} × ${i.katsayi}`).join("; ")])satir.append(oge("td",metin));sec("butceler").append(satir);}}
function asamaGoster(){if(!sonuc||!sonuc.asamalar.length)return;const a=sonuc.asamalar[Number(sec("asama").value)-1];sec("asamaNo").textContent=`${a.numara} / ${sonuc.asamalar.length}`;sec("asamaSatirlari").replaceChildren();for(const d of a.disler){const satir=oge("tr");for(const metin of [d.fdi,...Object.keys(adlar).map(ad=>d.hareket[ad].toFixed(3)),d.yuk.toplam_yuk.toFixed(3),a.ankraj.aktif_disler.includes(d.fdi)?"Aktif":"Pasif destek"])satir.append(oge("td",String(metin)));sec("asamaSatirlari").append(satir);}sec("zaman").replaceChildren(...sonuc.asamalar.map(s=>oge("span",String(s.numara),s.numara===a.numara?"secili":"")));}
sec("asama").addEventListener("input",asamaGoster);
sec("hesapla").addEventListener("click",async()=>{temizle();sec("hata").textContent="";sec("hesapla").disabled=true;try{const gonderilen=sec("girdi").value;const yanit=await fetch("/api/v1/planla",{method:"POST",headers:{"Content-Type":"application/json"},body:gonderilen});const rapor=await yanit.json();if(!yanit.ok)throw new Error(rapor.hata);if(sec("girdi").value!==gonderilen)throw new Error("Hesaplama sırasında girdi değişti; yeniden hesaplayın.");sonuc=rapor;sec("indir").disabled=false;const hedef=sec("ozet");hedef.replaceChildren(oge("div",durumlar[sonuc.durum]||sonuc.durum,"durum"));const kutular=oge("div",undefined,"istatistikler");for(const [deger,aciklama] of [[sonuc.ark_alt_siniri,"Sert limit alt sınırı"],[sonuc.ark_birlesik_yol_tahmini,"Birleşik yol tahmini"],[sonuc.asama_sayisi,"Üretilen taslak aşama"]]){const kutu=oge("div",undefined,"istatistik");kutu.append(oge("strong",String(deger)),oge("span",aciklama));kutular.append(kutu);}hedef.append(kutular,oge("p",`Hedef dağıtımı: ${sonuc.tamamlandi?"tamamlandı":"tamamlanmadı"}. Klinik onay: yok. Geometri doğrulaması: ${sonuc.geometri_dogrulandi?"dış denetçi tamamladı":"yok"}.`));for(const d of sonuc.disler.filter(d=>d.tahmin.birlesik_yol_tahmini>0)){const kutu=oge("div",undefined,"satir");kutu.append(oge("strong",`Diş ${d.fdi}`),oge("p",`Hasta öngörülebilirliği: hesaplanmadı. ${d.ongorulebilirlik.aciklama}`));if(d.ongorulebilirlik.literatur_araligi)kutu.append(oge("p",`Çalışmalar arası rotasyon doğruluğu: %${d.ongorulebilirlik.literatur_araligi.map(v=>Math.round(v*100)).join("–")} (hasta tahmini değildir).`,"kucuk"));if(d.atasman_senaryosu)kutu.append(oge("p",`Ataşman senaryosu: ${d.atasman_senaryosu.mevcut_tahmin} → ${d.atasman_senaryosu.planli_atasman_tahmini} tahmini aşama. ${d.atasman_senaryosu.aciklama}`,"kucuk"));hedef.append(kutu);}for(const b of sonuc.bulgular)hedef.append(oge("p",b));sec("asama").max=Math.max(1,sonuc.asama_sayisi);sec("asama").value=1;sec("asama").disabled=!sonuc.asama_sayisi;butceGoster();asamaGoster();}catch(h){sec("hata").textContent=h.message;}finally{sec("hesapla").disabled=false;}});
sec("indir").addEventListener("click",()=>{if(!sonuc)return;const adres=URL.createObjectURL(new Blob([JSON.stringify(sonuc,null,2)],{type:"application/json"}));const a=oge("a");a.href=adres;a.download="hareket-butcesi-taslak.json";a.click();setTimeout(()=>URL.revokeObjectURL(adres),1000);});
async function bilgi(){try{const veri=await(await fetch("/api/v1/bilgi")).json();for(const k of veri.kaynaklar){const kutu=oge("div",undefined,"kaynak"),bag=oge("a",`${k.kimlik} · ${k.yil} · ${k.baslik}`);bag.href=k.url;bag.target="_blank";bag.rel="noopener noreferrer";kutu.append(bag,oge("p",k.bulgu),oge("p",k.sinir));sec("kaynaklar").append(kutu);}}catch(h){sec("hata").textContent=h.message;}}
ornek();bilgi();
